# config/yaml/User.dcm.yml
CrossReference:
  type: entity
  table: cross_reference
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    last_update:
      type: datetime