# config/yaml/Timeframe.dcm.yml
TimeFrame:
  type: entity
  table: time_frame
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    minutes:
      type: integer
    last_update:
      type: datetime
    user_id:
      type: integer